name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main   # déclenche à chaque push sur main (change si besoin)

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Installer Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20   # Angular 17/18 supporte Node 20

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm ci

      # 4. Build Angular
      - name: Build Angular
        run: npm run build -- --configuration production --base-href "/${{ github.event.repository.name }}/"

      # 5. Déployer sur GitHub Pages (branche gh-pages)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/sned-fo-front
